name = "lobsterpot-positions"
main = "worker.js"
compatibility_date = "2025-04-01"
workers_dev = true

[[durable_objects.bindings]]
name = "POSITION_ROOM"
class_name = "ClanPositionRoom"

[[durable_objects.bindings]]
name = "BOUNTY_ROOM"
class_name = "BountyRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ClanPositionRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["BountyRoom"]
