package com.lobsterpot;

import net.runelite.client.config.Config;
import net.runelite.client.config.ConfigGroup;
import net.runelite.client.config.ConfigItem;

@ConfigGroup(LobsterPotConfig.GROUP)
public interface LobsterPotConfig extends Config
{
	String GROUP = "lobsterpot";
	String DEFAULT_PLUGIN_FEED_URL = "https://raw.githubusercontent.com/datlalo/lobsterpot-plugin-feed/refs/heads/main/plugin-feed.json";

	@ConfigItem(
		keyName = "pluginFeedUrl",
		name = "Plugin feed URL",
		description = "Public read-only JSON feed generated by the Discord bot.",
		position = 0,
		hidden = true
	)
	default String pluginFeedUrl()
	{
		return DEFAULT_PLUGIN_FEED_URL;
	}
}
